project:
  type: website
  preview:
    port: 7225
    browser: false

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: Pulse
    css: styles.css
  pdf:
    documentclass: scrartcl
    papersize: letter
  revealjs:
    scrollable: true