# AUTOGENERATED! DO NOT EDIT! File to edit: ../perception-prioritized-training-of-diffusion-models/Perception Prioritized Training of Diffusion Models.ipynb.

# %% auto 0
__all__ = []

# %% ../perception-prioritized-training-of-diffusion-models/Perception Prioritized Training of Diffusion Models.ipynb 1
from fastai.basics import *
from itertools import accumulate
